"""
test_pipeline.py
================
Tests del pipeline de MLOps: guardado/carga del artefacto, predicción sobre vinos nuevos
y garantías de que no se re-entrena ningún objeto durante la inferencia.

Uso / Usage:
    pytest tests/test_pipeline.py
"""

import sys
from pathlib import Path

import joblib          # Para guardar y cargar el artefacto en los tests / To save and load the artifact in tests
import numpy as np     # Para comparar arrays (assert_array_equal) / To compare arrays (assert_array_equal)
import pandas as pd    # Para leer el CSV generado por append_to_catalog / To read the CSV generated by append_to_catalog
import pytest          # Framework de tests: fixtures, assert, tmp_path / Test framework: fixtures, assert, tmp_path
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Añade la raíz del proyecto al path para poder importar src/ y preprocessing/
# Adds the project root to the path so we can import src/ and preprocessing/
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "preprocessing"))

# Importa las funciones que vamos a testear / Imports the functions we're going to test
from src.predict_pipeline import append_to_catalog, predict_from_artifacts  # noqa: E402

# ──────────────────────────────────────────────────────────────────────────────
# Constantes que replican las del pipeline real (deben coincidir exactamente)
# Constants that replicate those from the real pipeline (must match exactly)
# ──────────────────────────────────────────────────────────────────────────────

# Las 5 familias aromáticas definidas en preprocessing/mappings.py
# The 5 aroma families defined in preprocessing/mappings.py
FLAVOR_FAMILIES = [
    "fruta_roja_negra",
    "fruta_blanca_tropical",
    "madera_especias",
    "confiteria_tierra",
    "floral_mineral",
]

# Lista de columnas numéricas en el mismo orden que usa preprocessing.py para escalar
# Si el orden cambia aquí pero no en preprocessing.py (o viceversa), los tests fallarán
# List of numeric columns in the same order that preprocessing.py uses for scaling
# If the order changes here but not in preprocessing.py (or vice versa), tests will fail
NUMERIC_COLS = [
    "price_log",
    "rating",
    "quality_price_ratio",
    "year",
    "wine_ageing",
    "region_mean_price",
    "region_mean_rating",
    "grape_variety_mean_price",
    "grape_variety_mean_rating",
    "service_temp_midpoint",
] + [f"flavor_{f}" for f in FLAVOR_FAMILIES]  # Añade las 5 columnas de sabor al final / Adds the 5 flavor columns at the end


# ──────────────────────────────────────────────────────────────────────────────
# Funciones auxiliares para crear datos de prueba
# Helper functions to create test data
# ──────────────────────────────────────────────────────────────────────────────

def _make_wine_df(n: int = 3, region: str = "Rioja", grape: str = "Tempranillo") -> pd.DataFrame:
    """
    Crea un DataFrame sintético con n vinos de prueba.
    Los parámetros region y grape permiten probar casos conocidos y desconocidos.

    Creates a synthetic DataFrame with n test wines.
    The region and grape parameters allow testing known and unknown cases.
    """
    return pd.DataFrame(
        {
            "winery": [f"Bodega {i}" for i in range(n)],
            "wine_name": [f"Vino {i}" for i in range(n)],
            # La lista se repite con * y se recorta con [:n] para funcionar con cualquier n
            # The list repeats with * and is sliced with [:n] to work with any n
            "year": ([2018, 2019, 2020] * n)[:n],
            "rating": ([4.3, 4.5, 4.1] * n)[:n],
            "region": [region] * n,                  # Todos los vinos de la misma región / All wines from the same region
            "price_euros": ([25.0, 50.0, 100.0] * n)[:n],
            "vine_type": ["Tinto"] * n,
            "grape_variety": [grape] * n,
            "wine_ageing": ([0, 1, 0] * n)[:n],      # Alterna joven y crianza / Alternates young and aged
            "service_temperature": ["16-18°C"] * n,
            "quality_price_ratio": ([0.17, 0.09, 0.04] * n)[:n],
            "luxury_category": ([0, 0, 1] * n)[:n],
        }
    )


def _make_artifacts(n_clusters: int = 3) -> dict:
    """
    Crea un artefacto mínimo con objetos sklearn entrenados sobre datos aleatorios.
    No usa datos reales para que los tests sean rápidos e independientes del CSV.

    Creates a minimal artifact with sklearn objects trained on random data.
    Doesn't use real data so tests are fast and independent of the CSV.
    """
    # Generador de números aleatorios con semilla fija: los tests siempre dan el mismo resultado
    # Random number generator with fixed seed: tests always give the same result
    rng = np.random.default_rng(42)

    n_features = len(NUMERIC_COLS)  # Número de columnas que espera el scaler / Number of columns the scaler expects

    # Crea 60 filas de datos sintéticos con distribución normal
    # Creates 60 rows of synthetic data with normal distribution
    X_dummy = rng.standard_normal((60, n_features))

    # Entrena los tres objetos sobre los datos sintéticos
    # Trains the three objects on the synthetic data
    scaler = StandardScaler().fit(X_dummy)                                    # Aprende media y desviación / Learns mean and std
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=5).fit(X_dummy)  # Calcula centroides / Calculates centroids
    pca = PCA(n_components=2, random_state=42).fit(X_dummy)                   # Calcula componentes / Calculates components

    # Lista de nombres de columnas escaladas (igual que feature_columns en el pipeline real)
    # List of scaled column names (same as feature_columns in the real pipeline)
    feature_columns = [f"{c}_scaled" for c in NUMERIC_COLS]

    # Diccionario de Target Encoding sintético con algunas regiones y uvas conocidas
    # Synthetic Target Encoding dictionary with some known regions and grapes
    encodings = {
        "region": {
            "global_mean_price": 50.0,   # Fallback si la región no está en la tabla / Fallback if region is not in the table
            "global_mean_rating": 4.3,
            "region_stats": {
                "Rioja": {"region_mean_price": 55.0, "region_mean_rating": 4.35},
                "Penedes": {"region_mean_price": 42.0, "region_mean_rating": 4.28},
            },
        },
        "grape": {
            "global_mean_price": 50.0,
            "global_mean_rating": 4.3,
            "grape_variety_stats": {
                "Tempranillo": {
                    "grape_variety_mean_price": 48.0,
                    "grape_variety_mean_rating": 4.32,
                },
                "Garnacha": {
                    "grape_variety_mean_price": 38.0,
                    "grape_variety_mean_rating": 4.25,
                },
            },
        },
    }

    # Devuelve el diccionario con la misma estructura que el pipeline real
    # Returns the dictionary with the same structure as the real pipeline
    return {
        "scaler": scaler,
        "target_encodings": encodings,
        "kmeans": kmeans,
        "pca": pca,
        "feature_columns": feature_columns,
        "k": n_clusters,  # Número de clusters / Number of clusters
    }


# ──────────────────────────────────────────────────────────────────────────────
# Fixtures de pytest
# pytest Fixtures
# ──────────────────────────────────────────────────────────────────────────────
# Los fixtures son funciones que pytest ejecuta antes de cada test que los pide
# Evitan repetir el mismo código de preparación en cada test
# Fixtures are functions that pytest runs before each test that requests them
# They avoid repeating the same setup code in each test

@pytest.fixture
def artifacts():
    """Artefacto sintético listo para usar en los tests / Synthetic artifact ready to use in tests."""
    return _make_artifacts()


@pytest.fixture
def wine_df():
    """DataFrame sintético con 3 vinos de prueba / Synthetic DataFrame with 3 test wines."""
    return _make_wine_df()


# ──────────────────────────────────────────────────────────────────────────────
# Tests
# ──────────────────────────────────────────────────────────────────────────────

def test_artifact_save_and_load(tmp_path, artifacts):
    """
    Verifica que el artefacto se puede guardar en disco y cargar sin errores,
    y que las claves del diccionario se conservan.

    Verifies that the artifact can be saved to disk and loaded without errors,
    and that the dictionary keys are preserved.
    """
    # tmp_path es una carpeta temporal que pytest crea y borra automáticamente
    # tmp_path is a temporary folder that pytest creates and deletes automatically
    path = tmp_path / "test_pipeline.joblib"

    joblib.dump(artifacts, path)   # Guarda en disco / Saves to disk
    loaded = joblib.load(path)     # Carga desde disco / Loads from disk

    assert loaded is not None                              # El objeto existe / Object exists
    assert set(loaded.keys()) == set(artifacts.keys())    # Las claves coinciden / Keys match


def test_artifact_contains_required_keys(artifacts):
    """
    Verifica que el artefacto tiene todas las claves que el pipeline necesita.
    Verifies that the artifact has all the keys the pipeline needs.
    """
    required = {"scaler", "target_encodings", "kmeans", "pca", "feature_columns", "k"}
    # issubset comprueba que 'required' está contenido en las claves del artefacto
    # issubset checks that 'required' is contained in the artifact's keys
    assert required.issubset(set(artifacts.keys()))


def test_new_wine_gets_cluster_id(artifacts, wine_df):
    """
    Verifica que cada vino nuevo recibe un cluster_id válido (entre 0 y k-1).
    Verifies that each new wine receives a valid cluster_id (between 0 and k-1).
    """
    result = predict_from_artifacts(wine_df, artifacts)

    assert "cluster_id" in result.columns               # La columna existe / Column exists
    assert result["cluster_id"].notna().all()            # Sin valores nulos / No null values
    assert result["cluster_id"].between(0, artifacts["k"] - 1).all()  # Valores en rango válido / Values in valid range


def test_pc1_and_pc2_generated(artifacts, wine_df):
    """
    Verifica que el pipeline genera PC1 y PC2 sin valores nulos.
    Verifies that the pipeline generates PC1 and PC2 without null values.
    """
    result = predict_from_artifacts(wine_df, artifacts)

    assert "PC1" in result.columns
    assert "PC2" in result.columns
    assert result["PC1"].notna().all()
    assert result["PC2"].notna().all()


def test_row_count_preserved(artifacts, wine_df):
    """
    Verifica que el número de filas de entrada y salida es el mismo.
    Verifies that the number of input and output rows is the same.
    """
    result = predict_from_artifacts(wine_df, artifacts)
    assert len(result) == len(wine_df)  # Mismas filas / Same rows


def test_feature_columns_match_scaler(artifacts):
    """
    Verifica que feature_columns tiene exactamente el mismo número de columnas
    que el scaler espera recibir (evita errores de dimensionalidad).

    Verifies that feature_columns has exactly the same number of columns
    that the scaler expects to receive (avoids dimensionality errors).
    """
    # n_features_in_ es el número de features con el que fue entrenado el scaler
    # n_features_in_ is the number of features the scaler was trained with
    assert len(artifacts["feature_columns"]) == artifacts["scaler"].n_features_in_


def test_unknown_region_and_grape_handled(artifacts):
    """
    Verifica que una región o uva que no estaba en el entrenamiento
    no lanza un error: usa la media global como fallback.

    Verifies that a region or grape not seen during training
    doesn't raise an error: uses the global mean as fallback.
    """
    # Crea vinos con región y uva desconocidas / Creates wines with unknown region and grape
    df_unknown = _make_wine_df(n=2, region="RegionDesconocida", grape="UvaDesconocida")
    result = predict_from_artifacts(df_unknown, artifacts)

    # El pipeline no debe fallar, solo usar valores por defecto
    # The pipeline must not fail, only use default values
    assert result["cluster_id"].notna().all()
    assert result["PC1"].notna().all()
    assert result["PC2"].notna().all()


def test_no_refitting_during_prediction(artifacts, wine_df):
    """
    Verifica que predict_from_artifacts no re-entrena el scaler.
    Si se llamara .fit() en lugar de .transform(), la media cambiaría.

    Verifies that predict_from_artifacts doesn't retrain the scaler.
    If .fit() were called instead of .transform(), the mean would change.
    """
    # Guarda una copia de la media del scaler antes de predecir
    # Saves a copy of the scaler's mean before predicting
    mean_before = artifacts["scaler"].mean_.copy()

    predict_from_artifacts(wine_df, artifacts)  # Ejecuta la predicción / Runs the prediction

    # La media debe ser exactamente la misma después de predecir
    # The mean must be exactly the same after predicting
    np.testing.assert_array_equal(artifacts["scaler"].mean_, mean_before)


def test_feature_column_order_matches_unscaled(artifacts):
    """
    Verifica que todas las columnas en feature_columns terminan en "_scaled".
    Garantiza que la lógica de quitar el sufijo en predict funciona correctamente.

    Verifies that all columns in feature_columns end with "_scaled".
    Guarantees that the suffix-removal logic in predict works correctly.
    """
    for col in artifacts["feature_columns"]:
        assert col.endswith("_scaled"), f"Columna inesperada sin sufijo _scaled: {col}"


def test_append_to_catalog_writes_correct_columns(tmp_path, artifacts, wine_df):
    """
    Verifica que append_to_catalog solo escribe las columnas que loader.py necesita,
    descartando columnas internas del pipeline (PC1, PC2, price_log...).

    Verifies that append_to_catalog only writes the columns that loader.py needs,
    discarding internal pipeline columns (PC1, PC2, price_log...).
    """
    result = predict_from_artifacts(wine_df, artifacts)

    csv_path = tmp_path / "catalog.csv"  # Archivo temporal para el test / Temporary file for the test
    n = append_to_catalog(result, csv_path)

    assert n == len(wine_df)               # Devuelve el número correcto de filas / Returns the correct number of rows

    written = pd.read_csv(csv_path)        # Lee el CSV generado / Reads the generated CSV
    assert "cluster_id" in written.columns # cluster_id debe estar / cluster_id must be there
    assert len(written) == len(wine_df)    # Mismo número de filas / Same number of rows

    # Estas columnas son internas del pipeline y NO deben aparecer en el catálogo
    # These columns are internal to the pipeline and must NOT appear in the catalog
    assert "PC1" not in written.columns
    assert "price_log" not in written.columns


def test_append_to_catalog_appends_without_overwriting(tmp_path, artifacts, wine_df):
    """
    Verifica que llamar a append_to_catalog dos veces acumula filas,
    no sobreescribe las anteriores (mode="a" en to_csv).

    Verifies that calling append_to_catalog twice accumulates rows,
    doesn't overwrite the previous ones (mode="a" in to_csv).
    """
    result = predict_from_artifacts(wine_df, artifacts)
    csv_path = tmp_path / "catalog.csv"

    append_to_catalog(result, csv_path)  # Primera escritura / First write
    append_to_catalog(result, csv_path)  # Segunda escritura, debe acumular / Second write, must accumulate

    written = pd.read_csv(csv_path)
    # El doble de filas confirma que no sobreescribió / Double rows confirms it didn't overwrite
    assert len(written) == len(wine_df) * 2
