"""
UI metadata for each wine cluster profile.
Metadatos de UI para cada perfil de cluster de vinos.

Kept separate from clusters.py because that file is auto-generated by
04_clustering.ipynb and would overwrite any additions.

Separado de clusters.py porque ese archivo es auto-generado por
04_clustering.ipynb y sobreescribiría cualquier añadido.
"""

PROFILE_UI: dict[int, dict] = {
    0: {
        "color":           "#8B0000",
        "bg":              "rgba(139,0,0,0.08)",
        "border":          "rgba(139,0,0,0.25)",
        "color_dark":      "#F07880",
        "bg_dark":         "rgba(240,120,128,0.20)",
        "border_dark":     "rgba(240,120,128,0.48)",
        "icon_name":       "trophy",
        "characteristics": ["Alta gama", "Larga crianza", "Coleccionista", "D.O. Premium"],
        "temp":            "16-18°C",
        "flavors":         ["Cereza negra", "Ciruela", "Cedro", "Especias", "Tabaco", "Mineral"],
    },
    1: {
        "color":           "#C8A951",
        "bg":              "rgba(200,169,81,0.08)",
        "border":          "rgba(200,169,81,0.25)",
        "color_dark":      "#E8C060",
        "bg_dark":         "rgba(232,192,96,0.22)",
        "border_dark":     "rgba(232,192,96,0.50)",
        "icon_name":       "star",
        "characteristics": ["Blanco", "Aromático", "Elegante", "Media-alta gama"],
        "temp":            "8-10°C",
        "flavors":         ["Cítricos", "Melocotón", "Manzana verde", "Floral", "Mineral"],
    },
    2: {
        "color":           "#722F37",
        "bg":              "rgba(114,47,55,0.08)",
        "border":          "rgba(114,47,55,0.25)",
        "color_dark":      "#E07890",
        "bg_dark":         "rgba(224,120,144,0.20)",
        "border_dark":     "rgba(224,120,144,0.48)",
        "icon_name":       "gem",
        "characteristics": ["Tinto joven", "Sin crianza", "Regiones emergentes", "Precio medio"],
        "temp":            "14-16°C",
        "flavors":         ["Fruta roja fresca", "Violeta", "Frambuesa", "Especias", "Mineral"],
    },
    3: {
        "color":           "#6B7280",
        "bg":              "rgba(107,114,128,0.08)",
        "border":          "rgba(107,114,128,0.25)",
        "color_dark":      "#A8B0BC",
        "bg_dark":         "rgba(168,176,188,0.20)",
        "border_dark":     "rgba(168,176,188,0.42)",
        "icon_name":       "leaf",
        "characteristics": ["Tipo diverso", "Asequible", "Sorprendente", "Poco convencional"],
        "temp":            "12-16°C",
        "flavors":         ["Fruta", "Mineral", "Herbal", "Floral"],
    },
    4: {
        "color":           "#92400E",
        "bg":              "rgba(146,64,14,0.08)",
        "border":          "rgba(146,64,14,0.25)",
        "color_dark":      "#D4803C",
        "bg_dark":         "rgba(212,128,60,0.22)",
        "border_dark":     "rgba(212,128,60,0.50)",
        "icon_name":       "celebrate",
        "characteristics": ["Generoso", "Jerez", "Complejo", "Maridaje especial"],
        "temp":            "8-14°C",
        "flavors":         ["Frutos secos", "Caramelo", "Sal marina", "Avellana", "Toffee"],
    },
    5: {
        "color":           "#D97706",
        "bg":              "rgba(217,119,6,0.08)",
        "border":          "rgba(217,119,6,0.25)",
        "color_dark":      "#F0B030",
        "bg_dark":         "rgba(240,176,48,0.22)",
        "border_dark":     "rgba(240,176,48,0.50)",
        "icon_name":       "wine-glass-bubbles",
        "characteristics": ["Espumoso", "Cava", "Con crianza", "Celebración"],
        "temp":            "6-8°C",
        "flavors":         ["Brioche", "Manzana verde", "Cítricos", "Floral", "Levadura"],
    },
    6: {
        "color":           "#991B1B",
        "bg":              "rgba(153,27,27,0.08)",
        "border":          "rgba(153,27,27,0.25)",
        "color_dark":      "#E06065",
        "bg_dark":         "rgba(224,96,101,0.20)",
        "border_dark":     "rgba(224,96,101,0.48)",
        "icon_name":       "strength",
        "characteristics": ["Tinto", "Crianza en barrica", "Rioja / Ribera", "Clásico español"],
        "temp":            "16-18°C",
        "flavors":         ["Cereza madura", "Vainilla", "Roble", "Cuero", "Especias", "Tostado"],
    },
    7: {
        "color":           "#B91C1C",
        "bg":              "rgba(185,28,28,0.08)",
        "border":          "rgba(185,28,28,0.25)",
        "color_dark":      "#F07085",
        "bg_dark":         "rgba(240,112,133,0.20)",
        "border_dark":     "rgba(240,112,133,0.48)",
        "icon_name":       "heart",
        "characteristics": ["Tinto joven", "D.O. Premium", "El más popular", "Media-alta gama"],
        "temp":            "14-16°C",
        "flavors":         ["Fruta roja", "Mora", "Violeta", "Especias suaves", "Taninos frescos"],
    },
}
