"""
Wine data loader / Cargador de datos de vinos.

Loads the real wine dataset from wines_SPA_enriched.csv (generated by
04_clustering.ipynb) and normalises fields for use across the app.

Carga el dataset real de vinos desde wines_SPA_enriched.csv (generado por
04_clustering.ipynb) y normaliza los campos para su uso en la app.
"""

import pandas as pd
from pathlib import Path

_CSV_PATH = (
    Path(__file__).resolve().parent.parent.parent
    / "data" / "processed" / "wines_SPA_enriched.csv"
)

_REQUIRED_COLUMNS = {
    "winery", "wine_name", "year", "rating", "region",
    "price_euros", "vine_type", "grape_variety",
    "wine_ageing", "quality_price_ratio", "luxury_category", "cluster_id",
}

# wine_ageing in the CSV is a binary flag (0 = young, 1 = aged)
# wine_ageing en el CSV es un flag binario (0 = joven, 1 = con crianza)
_AGEING_LABEL: dict[int, str] = {0: "Joven", 1: "Crianza"}

# Keywords in wine name (lowercase) → inferred vine type, applied to "Desconocido" wines
_NAME_TYPE_RULES: list[tuple[str, str]] = [
    ("rosado",         "Rosado"),
    ("blanc",          "Blanco"),   # Blanco, Blanc, Vi Blanc, Lo Blanc, Blanca
    ("godello",        "Blanco"),
    ("viognier",       "Blanco"),
    ("gewurztraminer", "Blanco"),
    ("muscat",         "Blanco"),
    ("moscatel",       "Blanco"),
    ("malvasia",       "Blanco"),
    ("xarel",          "Blanco"),   # Xarel-lo
    ("parellada",      "Blanco"),
    ("marmajuelo",     "Blanco"),   # white grape from Canary Islands
    ("vermouth",       "Generoso"),
    ("vermu",          "Generoso"),
    ("vermut",         "Generoso"),
    ("palo cortado",   "Generoso"),
    ("fino",           "Generoso"),
    ("tintilla",       "Tinto"),
    ("mataro",         "Tinto"),    # Mataro = Monastrell (red grape)
]


# Manual type assignments for wines not inferable from name keywords alone
_MANUAL_TYPE: dict[str, str] = {
    "Sorte O Soro Val do Bibei":             "Blanco",   # Rafael Palacios, Valdeorras white
    "Molino Real":                            "Blanco",   # Telmo Rodríguez, Málaga Moscatel
    "Diables":                               "Tinto",    # Amos Baneres, Penedès red
    "Lapola":                                "Blanco",   # Galician white, Ribeira Sacra
    "No. 2 Victoria":                        "Blanco",   # Telmo Rodríguez, Málaga white
    "Nun Vinya dels Taus":                   "Blanco",   # Alta Alella white
    "Ekam Essencia":                         "Blanco",   # Gramona, Costers del Segre white
    "Ekam":                                  "Blanco",   # Gramona, Costers del Segre white
    "El Rocallis":                           "Blanco",   # Catalan white (Garnacha Blanca)
    "Gessami":                               "Blanco",   # Gramona aromatic white (Muscat, Gewurz, SB)
    "Navarra Vendimia Tardia Coleccion 125": "Blanco",   # Bodegas Ochoa, late-harvest Moscatel
}


def _infer_vine_type(name: str) -> str | None:
    if name in _MANUAL_TYPE:
        return _MANUAL_TYPE[name]
    name_lower = name.lower()
    for keyword, vine_type in _NAME_TYPE_RULES:
        if keyword in name_lower:
            return vine_type
    return None


def _load_wines() -> list[dict]:
    """Load, validate, normalise and index all wines from CSV."""
    if not _CSV_PATH.exists():
        raise FileNotFoundError(
            f"Dataset not found: {_CSV_PATH}\n"
            "Run notebooks/03_preprocessing.ipynb then "
            "notebooks/04_clustering.ipynb to generate it."
        )

    try:
        # utf-8-sig handles UTF-8 files with or without BOM automatically
        df = pd.read_csv(_CSV_PATH, encoding="utf-8-sig")
    except Exception as exc:
        raise RuntimeError(f"Failed to read dataset at {_CSV_PATH}: {exc}") from exc

    missing_cols = _REQUIRED_COLUMNS - set(df.columns)
    if missing_cols:
        raise ValueError(
            f"Dataset is missing required columns: {missing_cols}. "
            "Re-run the preprocessing and clustering notebooks."
        )

    df["wine_ageing"] = df["wine_ageing"].map(_AGEING_LABEL).fillna("Joven")
    df["luxury_category"] = df["luxury_category"].astype(bool)

    wines = df.to_dict("records")
    classified = []
    for wine in wines:
        wine.setdefault("flavor_descriptor", "")
        if wine.get("vine_type") == "Desconocido":
            inferred = _infer_vine_type(wine.get("wine_name", ""))
            if inferred:
                wine["vine_type"] = inferred
            else:
                continue  # drop wines with no classifiable type / descarta vinos sin tipo identificable
        classified.append(wine)

    # Assign sequential IDs only after dropping unclassifiable wines
    # Asigna IDs secuenciales solo después de descartar vinos sin clasificar
    for i, wine in enumerate(classified, start=1):
        wine["id"] = i

    return classified


WINES: list[dict] = _load_wines()
