"""
train_pipeline.py
=================
Entrena K-Means y PCA sobre wines_SPA_model_ready.csv (ya preprocesado por
los notebooks) y guarda todos los artefactos en models/inwine_pipeline.joblib.

El preprocesamiento real (escalado, encoding, OHE) lo hacen los notebooks;
este script solo retoma el CSV resultante y entrena los modelos de clustering.

Uso:
    python -m src.train_pipeline
"""

import pickle              # Para cargar el artefacto .pkl generado por el notebook / To load the .pkl artifact generated by the notebook
from pathlib import Path   # Para trabajar con rutas de archivo de forma segura / For safe file path handling

import joblib              # Guarda y carga objetos Python en disco (más eficiente que pickle) / Saves and loads Python objects to disk
import pandas as pd        # Manejo de tablas de datos / Data table handling
from sklearn.cluster import KMeans        # Algoritmo de clustering K-Means
from sklearn.decomposition import PCA     # Algoritmo de reducción de dimensionalidad

# Ruta raíz del proyecto (sube un nivel desde src/) / Project root path (one level up from src/)
ROOT = Path(__file__).resolve().parents[1]

# Ruta al CSV ya preprocesado por los notebooks (contiene las 18 columnas _scaled listas para el modelo)
# Path to the CSV already preprocessed by the notebooks (contains the 18 _scaled columns ready for the model)
DATA_PATH = ROOT / "data" / "processed" / "wines_SPA_model_ready.csv"

# Ruta al .pkl generado por el notebook 03_preprocessing.ipynb
# Contiene el StandardScaler ya entrenado, el mapa de precios por región y por uva
# Path to the .pkl generated by notebook 03_preprocessing.ipynb
# Contains the already trained StandardScaler, the price map per region and per grape
PKL_PATH = ROOT / "preprocessing" / "preprocessing_objects.pkl"

# Ruta donde se guardará el artefacto con todos los objetos entrenados
# Path where the artifact with all trained objects will be saved
MODEL_PATH = ROOT / "models" / "inwine_pipeline.joblib"

# Número de clusters — debe coincidir con los perfiles definidos en app/data/clusters.py
# Number of clusters — must match the profiles defined in app/data/clusters.py
K = 8

# Semilla aleatoria para reproducibilidad: con el mismo valor siempre da el mismo resultado
# Random seed for reproducibility: the same value always produces the same result
RANDOM_STATE = 42


def train(
    data_path: Path = DATA_PATH,
    pkl_path: Path = PKL_PATH,
    model_path: Path = MODEL_PATH,
) -> dict:
    """
    Lee el CSV ya preprocesado, entrena K-Means y PCA, y guarda el artefacto.
    Devuelve el diccionario de artefactos guardado.

    Reads the already preprocessed CSV, trains K-Means and PCA, and saves the artifact.
    Returns the saved artifacts dictionary.
    """

    # Carga el CSV de vinos ya preprocesado por los notebooks
    # Load the wine CSV already preprocessed by the notebooks
    df = pd.read_csv(data_path)
    print(f"Dataset cargado: {df.shape}")

    # Selecciona solo las columnas que terminan en "_scaled" (las 18 que uso el notebook de clustering)
    # Selects only columns ending in "_scaled" (the 18 the clustering notebook used)
    feature_columns = [c for c in df.columns if c.endswith("_scaled")]

    # Convierte el DataFrame a una matriz numpy (array de numeros) que sklearn entiende
    # Converts the DataFrame to a numpy matrix (number array) that sklearn understands
    X = df[feature_columns].values
    print(f"Features para clustering/PCA: {len(feature_columns)} columnas")
    print(feature_columns)

    # Abre el .pkl que genero el notebook 03_preprocessing.ipynb y carga todos sus objetos
    # Opens the .pkl generated by notebook 03_preprocessing.ipynb and loads all its objects
    with open(pkl_path, "rb") as f:
        preprocessing_objects = pickle.load(f)

    # StandardScaler ya entrenado con los datos originales: sabe la media y desviacion de cada columna
    # Already trained StandardScaler with the original data: knows the mean and std of each column
    scaler = preprocessing_objects["scaler"]

    # Diccionario {region: precio_medio} para transformar regiones en valores numericos durante la inferencia
    # Dictionary {region: mean_price} to transform regions into numeric values during inference
    region_price_map = preprocessing_objects["region_price_map"]

    # Diccionario {variedad_uva: precio_medio} para transformar uvas en valores numericos durante la inferencia
    # Dictionary {grape_variety: mean_price} to transform grapes into numeric values during inference
    grape_price_map = preprocessing_objects["grape_price_map"]

    # Lista de nombres de columnas sin escalar, en el mismo orden que uso el entrenamiento
    # List of unscaled column names, in the same order used during training
    model_features = preprocessing_objects["model_features"]
    print("Scaler y mapeos de preprocesamiento cargados.")

    # Crea el modelo K-Means con 8 clusters, semilla fija y 10 inicializaciones distintas
    # n_init=10 prueba 10 puntos de partida aleatorios y se queda con el mejor resultado
    # Creates K-Means with 8 clusters, fixed seed and 10 different initializations
    # n_init=10 tries 10 random starting points and keeps the best result
    kmeans = KMeans(n_clusters=K, random_state=RANDOM_STATE, n_init=10)

    # Entrena el modelo: calcula los 8 centroides sobre los datos
    # Trains the model: calculates the 8 centroids on the data
    kmeans.fit(X)

    # Cuenta cuantos vinos hay en cada cluster para mostrar la distribucion
    # Counts how many wines are in each cluster to show the distribution
    cluster_counts = dict(
        sorted(pd.Series(kmeans.labels_).value_counts().to_dict().items())
    )
    print(f"K-Means entrenado (K={K}). Distribucion: {cluster_counts}")

    # Crea el modelo PCA con 2 componentes (PC1 y PC2 para visualizacion en 2D)
    # Creates the PCA model with 2 components (PC1 and PC2 for 2D visualization)
    pca = PCA(n_components=2, random_state=RANDOM_STATE)

    # Entrena PCA: calcula las direcciones de maxima varianza en los datos
    # Trains PCA: calculates the directions of maximum variance in the data
    pca.fit(X)

    # Calcula que porcentaje de informacion conserva cada componente
    # Calculates what percentage of information each component preserves
    pc1_var = pca.explained_variance_ratio_[0] * 100
    pc2_var = pca.explained_variance_ratio_[1] * 100
    print(f"PCA entrenado - PC1: {pc1_var:.1f}%, PC2: {pc2_var:.1f}% de varianza explicada")

    # Crea la carpeta models/ si no existe (exist_ok=True evita error si ya existe)
    # Creates the models/ folder if it doesn't exist (exist_ok=True avoids error if it already exists)
    model_path.parent.mkdir(exist_ok=True)

    # Agrupa todos los objetos entrenados en un diccionario (la "caja")
    # Groups all trained objects in a dictionary (the "box")
    artifacts = {
        "scaler":           scaler,            # StandardScaler entrenado / Trained StandardScaler
        "region_price_map": region_price_map,  # Precio medio por region (fallback para vinos nuevos) / Mean price per region (fallback for new wines)
        "grape_price_map":  grape_price_map,   # Precio medio por uva (fallback para vinos nuevos) / Mean price per grape (fallback for new wines)
        "model_features":   model_features,    # Nombres de columnas sin escalar, en orden / Unscaled column names, in order
        "kmeans":           kmeans,            # Modelo K-Means entrenado con sus 8 centroides / Trained K-Means model with its 8 centroids
        "pca":              pca,               # Modelo PCA entrenado / Trained PCA model
        "feature_columns":  feature_columns,   # Nombres con _scaled, en orden exacto del entrenamiento / Names with _scaled, in exact training order
        "k":                K,                 # Numero de clusters (guardado como referencia) / Number of clusters (saved as reference)
    }

    # Serializa el diccionario y lo guarda en disco como archivo .joblib
    # Serializes the dictionary and saves it to disk as a .joblib file
    joblib.dump(artifacts, model_path)
    print(f"Artefacto guardado en: {model_path}")

    # Devuelve el diccionario para poder usarlo directamente sin releer el disco
    # Returns the dictionary so it can be used directly without re-reading from disk
    return artifacts


# Solo ejecuta train() si este archivo se llama directamente (no si se importa)
# Only runs train() if this file is called directly (not if it's imported)
if __name__ == "__main__":
    train()
